/* Executes the production worker protocol with real TFJS/Dawn Metal and local assets.
   No browser UI automation. Requires Node webgpu on a Metal-capable Mac. */
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {create,globals} from 'webgpu';
const require=createRequire(import.meta.url),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),lab=path.join(root,'docs/ciresan-stochastic-depth/browser-lab');
Object.assign(globalThis,globals);Object.defineProperty(globalThis,'navigator',{value:{gpu:create(['backend=metal'])},configurable:true});
globalThis.tf=await import('@tensorflow/tfjs');await import('@tensorflow/tfjs-backend-webgpu');
globalThis.MnistLabCore=require(path.join(lab,'core.js'));globalThis.createMnistEngine=require(path.join(lab,'tf-engine.js'));globalThis.MnistLabData=require(path.join(lab,'dataset.js'));globalThis.self=globalThis;globalThis.importScripts=()=>{};
const fetches=[];globalThis.fetch=async url=>{fetches.push(String(url));return new Response(fs.readFileSync(path.join(lab,String(url))),{status:200});};
let events=[],stopAtBatch=false;
globalThis.postMessage=m=>{events.push(m);if(m.type==='epoch')console.log(JSON.stringify({event:'epoch',run:m.runId,epoch:m.row.epoch,accuracy:m.row.validation.accuracy,loss:m.row.stochasticLoss}));if(m.type==='error')console.error('WORKER_ERROR',m.message);if(stopAtBatch&&m.type==='batch'){stopAtBatch=false;self.onmessage({data:{type:'stop'}});}};
vm.runInThisContext(fs.readFileSync(path.join(lab,'worker.js'),'utf8'),{filename:'production-worker.js'});
const start=Date.now(),config={preset:'small',plan:'paired',mask:15,trainN:4000,testN:2000,epochs:5,lr:.03,seed:201,dropRate:.5,batchSize:64,backend:'webgpu',order:[0,1,2,3]};
try{
 // Stop reaches the loader even when the first image response never arrives.
 const normalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{if(String(url).endsWith('train.bin.gz'))return new Promise((resolve,reject)=>{options.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true});setTimeout(()=>self.onmessage({data:{type:'stop'}}),0);});return normalFetch(url,options);};
 await self.onmessage({data:{type:'start',taskId:'native-download-stop',config}});assert(events.some(e=>e.type==='stopped'));assert.equal(events.filter(e=>e.type==='result').length,0);assert.equal(tf.memory().numTensors,0);globalThis.fetch=normalFetch;events=[];
 await self.onmessage({data:{type:'start',taskId:'native-worker-smoke',config}});
 assert.equal(events.filter(e=>e.type==='error').length,0);const results=events.filter(e=>e.type==='result').map(e=>e.run);assert.equal(results.length,2);assert.equal(events.at(-1).type,'done');
 for(const r of results){assert.equal(r.status,'complete');assert.equal(r.epochsCompleted,5);assert.equal(r.history.length,5);assert(r.endpoints.final.accuracy>.7,'Must learn real held-out MNIST');assert(r.history.at(-1).stochasticLoss<r.history[0].stochasticLoss);assert.equal(r.endpoints.selected.n,2000);assert.equal(r.provenance.testAccess,'only after training and checkpoint selection');assert(r.dropCounts.every(n=>r.config.mask===0?n===0:n>0));const best=Math.min(...r.history.map(h=>h.validation.ce));assert.equal(r.history[r.bestEpoch-1].validation.ce,best);}
 for(const k of ['initializationSHA256','orderHash','gateDrawHash','trainSHA256','validationSHA256','testSHA256'])assert.equal(results[0].provenance[k],results[1].provenance[k],k+' pairing');
 const before=tf.memory().numTensors;events=[];await self.onmessage({data:{type:'evaluate',endpoint:'selected',active:[true,true,true,true]}});let inferenceResult=events.find(e=>e.type==='inference');assert(inferenceResult);assert.equal(inferenceResult.score.accuracy,results.at(-1).endpoints.selected.accuracy);assert(Math.abs(inferenceResult.score.ce-results.at(-1).endpoints.selected.ce)<1e-6);assert.equal(tf.memory().numTensors,before);
 events=[];await self.onmessage({data:{type:'evaluate',endpoint:'final',active:[false,false,false,false]}});const noBranches=events.find(e=>e.type==='inference');assert(noBranches&&Number.isFinite(noBranches.score.ce));assert.equal(tf.memory().numTensors,before);
 events=[];stopAtBatch=true;await self.onmessage({data:{type:'start',taskId:'native-stop',config:{...config,preset:'tiny',plan:'single',epochs:2,trainN:1000}}});assert(events.some(e=>e.type==='stopped'));assert.equal(events.filter(e=>e.type==='result').length,0);assert.equal(tf.memory().numTensors,0,'Stop releases model, checkpoints and dataset tensors');
 events=[];await self.onmessage({data:{type:'start',taskId:'native-restart',config:{...config,preset:'tiny',plan:'single',epochs:1,trainN:1000}}});assert(events.some(e=>e.type==='result'),'Restart after Stop works');assert(!events.some(e=>e.type==='error'));
 const report={status:'passed',runtime:'Node execution of production worker; actual Dawn Metal WebGPU, no browser UI automation',tfjs:tf.version.tfjs,pairedConfig:config,pairedResults:results.map(r=>({mask:r.config.mask,selectedAccuracy:r.endpoints.selected.accuracy,finalAccuracy:r.endpoints.final.accuracy,selectedCE:r.endpoints.selected.ce,finalCE:r.endpoints.final.ce,bestEpoch:r.bestEpoch,timing:r.timing,provenance:r.provenance})),maskedInference:{active:noBranches.active,accuracy:noBranches.score.accuracy,ce:noBranches.score.ce},stopDuringStalledDownload:true,stopAndRestart:true,fullInferenceParity:true,noTensorLeakAcrossEvaluation:true,seconds:(Date.now()-start)/1000};
 fs.writeFileSync(new URL('./test-worker-webgpu.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'passed',seconds:report.seconds,pairedResults:report.pairedResults.map(r=>({mask:r.mask,accuracy:r.finalAccuracy,trainingSeconds:r.timing.trainingSeconds}))}));tf.backend().dispose();process.exit(0);
}catch(e){console.error(e.stack);process.exit(1);}
