/* Offline interface tests: jsdom and a simulated worker, not browser UI automation. */
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom'),Core=require('../../docs/ciresan-stochastic-depth/browser-lab/core.js');
const dir=path.resolve(__dirname,'../../docs/ciresan-stochastic-depth/browser-lab'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'dataset/manifest.json')));
const raw=zlib.gunzipSync(fs.readFileSync(path.join(dir,'dataset/test.bin.gz'))),count=raw.readUInt32LE(8),labelOffset=raw.readUInt32LE(24),indexOffset=raw.readUInt32LE(28);
const split={count,labels:new Uint8Array(raw.subarray(labelOffset,labelOffset+count)),pixels:new Uint8Array(raw.subarray(32,labelOffset)),indices:Uint32Array.from({length:count},(_,i)=>raw.readUInt32LE(indexOffset+4*i)),sha256:manifest.splits.test.sha256};
const preview=JSON.parse(fs.readFileSync(path.join(dir,'dataset/preview.json'))),tick=()=>new Promise(r=>setImmediate(r));let checks=0;
function ok(test,message){assert(test,message);checks++;}function equal(a,b,message){assert.deepEqual(a,b,message);checks++;}
function score(wrong=[],constant=null){const x=new Float32Array(count*10);for(let i=0;i<count;i++)x[i*10+(constant??(wrong.includes(i)?(split.labels[i]+1)%10:split.labels[i]))]=4;return Core.scores(x,split.labels);}
async function setup(){
 const dom=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{runScripts:'outside-only',url:'https://example.test/ciresan-stochastic-depth/browser-lab/'}),w=dom.window;
 let resolveData,rejectData,loadPromise=Promise.resolve(split),sent=[],exported;
 w.HTMLCanvasElement.prototype.getContext=()=>({createImageData:()=>({data:new Uint8ClampedArray(784*4)}),putImageData(){},drawImage(){}});
 w.fetch=async()=>({ok:true,json:async()=>preview});w.MnistLabCore=Core;w.MnistLabData={load:()=>loadPromise};
 w.Worker=class{postMessage(m){sent.push(m);}terminate(){}};w.URL.createObjectURL=b=>{exported=b;return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};
 w.eval(fs.readFileSync(path.join(dir,'app.js'),'utf8'));await tick();
 return {dom,w,$:id=>w.document.getElementById(id),sent,getExport:()=>exported,defer(){loadPromise=new Promise((resolve,reject)=>{resolveData=resolve;rejectData=reject;});},resolve(value=split){resolveData(value);},reject(){rejectData(Error('Test images unavailable'));},normal(){loadPromise=Promise.resolve(split);},emit(m){w.mnistBrowserLab.handleMessage(m);}};
}
function result(id,mask,cfg,wrong=[],overrides={}){const s=score(wrong);return{id,status:'complete',config:{...cfg,mask,actualBackend:'webgpu'},qualification:{backend:'webgpu',version:'4.22.0',attempts:[{backend:'webgpu',passed:true,seconds:.1}]},history:[{epoch:1,validation:{accuracy:.8,ce:.5},trainingSeconds:.4},{epoch:2,validation:{accuracy:.9,ce:.3},trainingSeconds:.8}],epochsCompleted:2,bestEpoch:2,endpoints:{selected:s,final:score([2,3])},timing:{trainingSeconds:.8,totalSeconds:1.4},provenance:{testSHA256:split.sha256},...overrides};}
(async()=>{
 const a=await setup(),{$,w}=a,change=id=>$(id).dispatchEvent(new w.Event('change',{bubbles:true}));
 equal($('digits').querySelectorAll('button').length,20,'real training preview');equal($('order').options.length,24,'every branch ordering available');equal($('learning-chart').querySelectorAll('circle').length,0,'no prerecorded measurements');
 $('plan').value='sweep';change('plan');ok(!$('order-label').hidden,'sweep shows order');ok([...$('training-branches').querySelectorAll('input')].every(x=>x.disabled),'sweep cannot imply ignored checkbox choice');$('order').value='3,2,1,0';equal(Core.queue(w.mnistBrowserLab.config()),[0,8,12,14,15],'reverse sweep');
 $('plan').value='paired';change('plan');$('epochs').value='2';$('training-branches').querySelectorAll('input')[1].checked=false;equal(w.mnistBrowserLab.config().mask,13,'branch selection');$('run').click();equal(a.sent[0].type,'start');equal(a.sent[0].config.mask,13);ok($('config-fields').disabled&&$('run').disabled&&!$('stop').disabled,'training locks config');const cfg=a.sent[0].config;
 a.emit({type:'backend',qualification:{backend:'webgpu',version:'4.22.0'}});ok($('backend-badge').textContent.includes('WEBGPU'));
 a.emit({type:'runStart',runId:'baseline',position:0,total:2,config:{...cfg,mask:0}});a.emit({type:'batch',runId:'baseline',position:0,total:2,epoch:1,epochs:2,fraction:.5,trainingSeconds:.1,active:[true,false,true,false]});equal($('network').querySelectorAll('.dropped').length,2,'live gates shown');ok($('progress').value>0);
 a.emit({type:'epoch',runId:'baseline',row:{epoch:1,validation:{accuracy:.8,ce:.5},trainingSeconds:.4},skipCounts:[0,0,0,0],steps:16});ok($('accuracy').textContent.includes('80.00'));equal($('learning-chart').querySelectorAll('circle').length,1);
 a.defer();const baseline=result('baseline',0,cfg,[1]);a.emit({type:'result',run:baseline});equal($('digits').querySelectorAll('button').length,0,'pending test data never mixes training preview and test predictions');equal($('probability-chart').querySelectorAll('rect').length,0);a.resolve();await tick();equal($('digits').querySelectorAll('button').length,48);equal($('probability-chart').querySelectorAll('rect').length,20);ok($('focus-label').textContent.includes('original #'+split.indices[0]));
 ok([...$('runs-table').querySelectorAll('button')].every(b=>b.disabled),'run cannot switch during plan');a.normal();const treatment=result('treatment',13,cfg,[0]);a.emit({type:'result',run:treatment});a.emit({type:'done',message:'Complete'});await tick();ok(!$('evaluate').disabled);ok($('gallery-note').textContent.includes('1 newly wrong and 1 repaired'),'paired example changes');
 $('outcome-filter').value='harmed';change('outcome-filter');equal($('digits').querySelectorAll('button').length,1);equal($('digits').querySelector('button').dataset.image,'0');$('outcome-filter').value='repaired';change('outcome-filter');equal($('digits').querySelector('button').dataset.image,'1');$('outcome-filter').value='all';change('outcome-filter');$('digit-filter').value='7';change('digit-filter');ok($('image-page').textContent.includes('200 matches'));$('digit-filter').value='all';change('digit-filter');$('next-images').click();ok($('image-page').textContent.includes('page 2/42'));
 $('chart-view').value='count';change('chart-view');equal($('learning-chart').querySelectorAll('circle').length,2);equal($('learning-chart').querySelectorAll('[stroke-dasharray]').length,1,'nested subset connected');
 const fullTable=$('runs-table').textContent,fullAccuracy=$('accuracy').textContent;[...$('inference-branches').querySelectorAll('input')].forEach(x=>x.checked=false);$('evaluate').click();equal(Array.from(a.sent.at(-1).active),[false,false,false,false]);ok($('endpoint').disabled);ok([...$('inference-branches').querySelectorAll('input')].every(x=>x.disabled));
 a.emit({type:'inference',runId:'treatment',endpoint:'selected',active:[false,false,false,false],score:score([],0),seconds:.2});equal($('accuracy').textContent,fullAccuracy,'main metric retains full-network result');equal($('runs-table').textContent,fullTable);ok($('gallery-title').textContent.includes('Inference'));ok($('inference-status').textContent.includes('10.00%'));ok($('status').textContent.includes('complete'));
 $('endpoint').value='final';change('endpoint');await tick();ok([...$('inference-branches').querySelectorAll('input')].every(x=>x.checked),'new checkpoint clears mask selection');ok(!$('gallery-title').textContent.includes('Inference'));equal($('accuracy').textContent,'99.90%');
 $('runs-table').querySelectorAll('button')[0].click();await tick();ok($('evaluate').disabled,'only latest model weights available');$('runs-table').querySelectorAll('button')[1].click();await tick();ok(!$('evaluate').disabled);
 const exportedBefore=w.mnistBrowserLab.getRuns().length;$('export').click();const exported=await new Promise(resolve=>{const reader=new w.FileReader();reader.onload=()=>resolve(JSON.parse(reader.result));reader.readAsText(a.getExport());});equal(exported.runs.length,exportedBefore);ok(Array.isArray(exported.runs[0].endpoints.selected.predictions),'typed predictions exported as arrays');equal(exported.inferencePreview,null);
 $('run').click();$('stop').click();equal(a.sent.at(-1).type,'stop');a.emit({type:'interrupted',runId:'stopped',status:'stopped',config:cfg,history:[],trainingSeconds:.02});a.emit({type:'stopped',message:'Stopped before test evaluation'});ok(!$('run').disabled&&$('stop').disabled);ok($('runs-table').textContent.includes('stopped'));ok(!w.mnistBrowserLab.getRuns().at(-1).endpoints,'stopped run has no test result');
 a.dom.window.close();
 // Nonnested masks are separate points, not an invented dropout ordering.
 const b=await setup();b.$('run').click();const bc=b.sent[0].config;b.emit({type:'result',run:result('one',1,bc)});b.emit({type:'result',run:result('two',6,bc)});b.emit({type:'done',message:'Complete'});await tick();b.$('chart-view').value='count';b.$('chart-view').dispatchEvent(new b.w.Event('change'));equal(b.$('learning-chart').querySelectorAll('[stroke-dasharray]').length,0,'nonnested masks stay unconnected');b.dom.window.close();
 // Exact held-out dataset identity is required; failure must not expose training previews.
 for(const failure of ['network','hash']){const c=await setup();c.$('run').click();c.defer();c.emit({type:'result',run:result(failure,0,c.sent[0].config)});c.emit({type:'done',message:'Complete'});if(failure==='network')c.reject();else c.resolve({...split,sha256:'incorrect'});await tick();equal(c.$('digits').querySelectorAll('button').length,0,failure+' cannot mislabel training images');equal(c.$('probability-chart').querySelectorAll('rect').length,0);ok(c.$('status').textContent.includes(failure==='network'?'unavailable':'does not match'));c.dom.window.close();}
 const report={status:'passed',runtime:'jsdom offline UI integration with simulated worker events; real MNIST assets; not a browser GPU benchmark',checks};fs.writeFileSync(path.join(__dirname,'test-page.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
})().catch(e=>{console.error(e);process.exit(1);});
